### ISSUE TITLE
v6.0.1 : throws an error `The "original" argument must be of type Function`

### ISSUE THREAD

**Issue by testtek** [sindresorhus/neat-csv#13] opened 2021-02-02 19:22 UTC
I wanted to use this package but it throws an error on initialization 

```const neatCSV = require('neat-csv')```

TypeError: The following error originated from your test code, not from Cypress.

  > The "original" argument must be of type Function

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

Check your console for the stack trace or click this message to see where it originated from.
    at promisify
    at Object../node_modules/neat-csv/node_modules/get-stream/index.js
    at __webpack_require__
    at Object.eval 
    at Object../node_modules/neat-csv/index.js 
    at __webpack_require__ 

How could we solve this?

**Comment by sindresorhus** [comment] 2021-02-02 20:46
Duplicate of #11

**Closed as completed by sindresorhus** 2021-02-02 20:46 UTC
